apiVersion: v1
kind: Pod
metadata:
  name: myApp
  labels:
    name: myApp
spec:
  containers:
  - name: fortune-https
    image: luksa/fortune:env
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: INTERVAL
        valueFrom:
            configMapKeyRef:
              key: sleep-Interval
              name: fortun-config
    volumeMounts:
      - name: html
        mountPath: /var/htdocs
  - name: web-server
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly: true
      - name : cert
        mountPath: /etx/nginx/certs/
        readOnly: true
  volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name : fortune-config
        items:
          - key: nginx.conf
            path: nginx-gzip.conf
    - name: cert
      secret:
          secretName: fortune-https