apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: openshift/mysql-55-centos7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '930611040'
            - name: MYSQL_USER
              value: afsan007
            - name: MYSQL_PASSWORD
              value: '457523'
            - name: MYSQL_DATABASE
              value: wp_db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql/data
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: claim-mysql
  - apiVersion: v1
    kind: Pod
    metadata:
      name: www
      labels:
        name: www
    spec:
      containers:
        - name: www
          image: nginx
          ports:
            - containerPort: 80
              name: www
          volumeMounts:
            - name: www-pv
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www-pv
          persistentVolumeClaim:
            claimName: claim-http
