apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nfs-pv1
    spec:
      storageClassName: manual
      persistentVolumeReclaimPolicy: Recycle
      accessModes:
        - ReadWriteOnce
        - ReadWriteMany
      capacity:
        storage: 2Gi
      nfs:
        server: 172.17.0.32
        path: /exports/data-0001
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nfs-pv2
    spec:
      storageClassName: manual
      persistentVolumeReclaimPolicy: Recycle
      accessModes:
        - ReadWriteOnce
        - ReadWriteMany
      capacity:
        storage: 2Gi
      nfs:
        server: 172.17.0.32
        path: /exports/data-0002
