cat <<EOF>> deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: pvc-nfs-pv1
      containers:
      - name: nginx
        image: nginx 
        volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
EOF