apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  app: nginx
spec:
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 50%
   maxUnavailable: 0
 minReadySeconds: 30
 replicas: 10
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
    - name: nginx
      image: nginx:1.7.4
      resources:
       limits:
        cpu: '250m'
        memory: '250Mi'
      readinessProbe:
       periodSeconds: 1
       httpGet:
        path: /
        port: 80
      ports:
       - containerPort: 80
