apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: appsecret
      items:
        - key: username
          path: '.username'
  containers:
  - name: dotfile-test-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"