apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: luksa/fortune   
    name: test-container
    volumeMounts:
    - mountPath: /var/htdocs 
      name: test-volume
  - image: nginx:alpine                  
    name: web-server                     
    volumeMounts:                        
    - name: test-volume                         
      mountPath: /usr/share/nginx/html    
      readOnly: true                      
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory