apiVersion: v1
kind: Pod
metadata:
  name: initContainers
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: '500m'
          memory: '700Mi'
      ports:
        - containerPort: 80
      volumeMounts:
        - name: work-dir
          mountPath: /usr/share/nginx/html
  initContainers: # These containers are run during pod initialization
    - name: install
      image: busybox
      command:
        - wget
        - '-O'
        - '/work-dir/index.html'
        - http://kubernetes.io
      volumeMounts:
        - name: work-dir
          mountPath: '/work-dir'
  dnsPolicy: Default
  volumes:
    - name: work-dir
      emptyDir: {}
