apiVersion: v1
kind: Pod
metadata:
  name: fortun-test
  labels:
    name: test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: nginx-gzip.conf
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    ports:
      - containerPort: 5000
  volumes:
    - name: config
      configMap:
          name: fortun-map
          items:
            - key: nginx.conf
              path: nginx-gzip.conf
    - name: secret
      secret:
          
            