
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  revisionHistoryLimit: 20
  replicas: 3
  selector:
    matchLabels:
      component: replica
    matchExpressions:
      - 
  template:
    metadata:
      labels:
        component: replica
      
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 8000
