apiVersion: v1
kind: Pod
metadata:
  name: myApp
  labels:
    name: myApp
spec:
  containers:
  - name: myApp
    image: nginx
    volumeMounts:
      - name: secrets
        mountPath: 'etc/secrets'
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
  volumes:
    - name: secrets
      secret:
          secretName: mysecret
          items:
            - key: username
              path: 'log'
              mode: 256