apiVersion: v1
kind: List
items:

 - apiVersion: scheduling.k8s.io/v1
   kind: PriorityClass
   metadata:
    name: high-priority-nonpreempting
   value: 1000
   preemptionPolicy: Never
   globalDefault: false
   description: "priorityClass: High"

 - apiVersion: scheduling.k8s.io/v1
   kind: PriorityClass
   metadata:
    name: medium-priority-nonpreempting
   value: 500
   preemptionPolicy: Never
   globalDefault: false
   description: "priorityClass: Medium"

 - apiVersion: scheduling.k8s.io/v1
   kind: PriorityClass
   metadata:
    name: low-priority-nonpreempting
   value: 250
   preemptionPolicy: Never
   globalDefault: false
   description: "priorityClass: Low"
 - apiVersion: v1
