apiVersion: v1
kind: List
items:
 - apiVersion: v1
   kind: LimitRange
   metadata:
    name: container-resource
   spec:
    limits:
     - max:
        cpu: 1
        memory: '1Gi'
       min:
        cpu: .2
        memory: '100Mi'
       default:
        cpu: .3
        memory: '500Mi'
       defaultRequest:
        cpu: '210m'
        memory: '300Mi'
       type: Container
 - apiVersion: v1
   kind: LimitRange
   metadata:
    name: container-resource-1
   spec:
    limits:
     - max:
        cpu: 3
        memory: '4Gi'
       min:
        cpu: .2
        memory: '100Mi'
       type: Pod
 - apiVersion: v1
   kind: ResourceQuota
   metadata:
    name: compute-resource
    namespace: dev
   spec:
    hard:
     requests.cpu: '5'
     requests.memory: '3Gi'
     limits.cpu: '7'
     limits.memory: '8Gi'
 - apiVersion: v1
   kind: ResourceQuota
   metadata:
    name: object-counts
    namespace: prod
   spec:
    hard:
     configmaps: '10'
     pods: '10'
     secrets: '10'
     services: '5'
     services.loadbalancers: '6'
