apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
  labels:
    type: local
spec:
  nfs:
    path: '/mnt/sharedfolder/pv0'
    server: 172.17.0.7
  storageClassName: manual

  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    type: local
spec:
  nfs:
    path: '/mnt/sharedfolder/pv1'
    server: 172.17.0.7
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
  labels:
    type: local
spec:
  nfs:
    path: '/mnt/sharedfolder/pv2'
    server: 172.17.0.7
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv3
  labels:
    type: local
spec:
  nfs:
    path: '/mnt/sharedfolder/pv3'
    server: 172.17.0.7
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv4   
  labels:
    type: local
spec:
  nfs:
    path: '/mnt/sharedfolder/pv4'
    server: 172.17.0.7
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
