apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
spec:
  containers:
    - name: test
      image: k8s.gcr.io/busybox
      resources:
        limits:
          cpu: '500m'
          memory: '200Mi'
      command: ['/bin/sh', '-c', 'env']
      env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: environment
  restartPolicy: Never
