apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: pod-config-map
    spec:
      containers:
        - name: test
          image: k8s.gcr.io/busybox
          resources:
            limits:
              cpu: '500m'
              memory: '200Mi'
          command: ['/bin/sh', '-c', 'echo $(ENVIRONMENT)']
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: general-config
                  key: environment
      restartPolicy: Never
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: general-config
    data:
      environment: production
